{{- if not .Values.scaleway.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaleway-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scaleway-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  SCALEWAY_TOKEN: {{ required "scaleway.token is required when scaleway.existingSecret is not set" .Values.scaleway.token | quote }}
  SCALEWAY_ORG_ID: {{ required "scaleway.organizationId is required when scaleway.existingSecret is not set" .Values.scaleway.organizationId | quote }}
{{- end }}
