{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaleway-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scaleway-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "scaleway-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
{{- end }}
